const fs = require('fs');
const path = require('path');
const https = require('https');

const mockDbPath = path.join(__dirname, 'apps', 'shared', 'mockDb.ts');
const assetsDir = path.join(__dirname, 'apps', 'assets', 'brand_logos');

if (!fs.existsSync(assetsDir)) {
  fs.mkdirSync(assetsDir, { recursive: true });
}

// Read mockDb.ts
const content = fs.readFileSync(mockDbPath, 'utf8');

// Extract initialBrands array content
const startMarker = 'export const initialBrands: Brand[] = [';
const startIndex = content.indexOf(startMarker);
if (startIndex === -1) {
  console.error("Could not find initialBrands in mockDb.ts");
  process.exit(1);
}

// Find matching closing bracket ]; for the array
let bracketCount = 1;
let endIndex = startIndex + startMarker.length;
while (bracketCount > 0 && endIndex < content.length) {
  if (content[endIndex] === '[') bracketCount++;
  else if (content[endIndex] === ']') bracketCount--;
  endIndex++;
}

const brandsSub = content.slice(startIndex, endIndex);

// Parse brand name and logo
const brandRegex = /name:\s*"([^"]+)"[\s\S]*?logo:\s*"([^"]+)"/g;
let match;
const brands = [];
while ((match = brandRegex.exec(brandsSub)) !== null) {
  brands.push({ name: match[1], logoUrl: match[2] });
}

console.log(`Found ${brands.length} brands in mockDb.ts`);

const downloadedBrands = [];

function sanitizeFileName(name) {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_');
}

function downloadLogo(brand, index) {
  if (index >= brands.length) {
    generateMappingFile();
    return;
  }

  const { name, logoUrl } = brand;
  const fileName = `${sanitizeFileName(name)}.png`;
  const filePath = path.join(assetsDir, fileName);

  console.log(`[${index + 1}/${brands.length}] Downloading logo for ${name}...`);

  // Clearbit and other hosts might return 403 if request is not clean
  const request = https.get(logoUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
    }
  }, (response) => {
    if (response.statusCode === 200) {
      const fileStream = fs.createWriteStream(filePath);
      response.pipe(fileStream);
      fileStream.on('finish', () => {
        fileStream.close();
        console.log(`Successfully saved ${name} logo.`);
        downloadedBrands.push({ name, fileName });
        setTimeout(() => downloadLogo(brands[index + 1], index + 1), 50);
      });
    } else {
      console.warn(`Failed to download ${name} logo. HTTP Status: ${response.statusCode}`);
      setTimeout(() => downloadLogo(brands[index + 1], index + 1), 50);
    }
  });

  request.on('error', (err) => {
    console.error(`Error downloading ${name} logo:`, err.message);
    setTimeout(() => downloadLogo(brands[index + 1], index + 1), 50);
  });
}

function generateMappingFile() {
  const mappingFilePath = path.join(__dirname, 'apps', 'shared', 'brandLogos.ts');
  let fileContent = `// This file is auto-generated by download_logos.js\n\n`;
  fileContent += `export const BRAND_LOGOS: Record<string, any> = {\n`;

  downloadedBrands.forEach(b => {
    fileContent += `  "${b.name}": require('../assets/brand_logos/${b.fileName}'),\n`;
  });

  fileContent += `};\n`;

  fs.writeFileSync(mappingFilePath, fileContent, 'utf8');
  console.log(`Generated logo mapping file at ${mappingFilePath}`);
  console.log(`Total downloaded logos: ${downloadedBrands.length}`);
}

// Start download
downloadLogo(brands[0], 0);
